<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEFSnunO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEFSnunO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEFSnunO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEFSnunO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEFSnunO\App_KernelDevDebugContainer([
    'container.build_hash' => 'EFSnunO',
    'container.build_id' => 'f40be0a2',
    'container.build_time' => 1580507580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEFSnunO');
